---
- name: Deploy and run PetClinic application
  hosts: web_server
  remote_user: runhaix
  gather_facts: no
  
  tasks:
    - name: Create a directory for the PetClinic app
      become: yes
      file:
        path: /opt/petclinic
        state: directory

    - name: Fetch PetClinic JAR file from Jenkins
      delegate_to: localhost
      fetch:
        src: /var/jenkins_home/workspace/deploy_using_ansible/target/petclinic.jar
        dest: /tmp/petclinic.jar
        flat: yes

    - name: Copy PetClinic JAR file to target machine
      become: yes
      copy:
        src: /tmp/petclinic.jar
        dest: /opt/petclinic/spring-petclinic.jar
        mode: 0644
     
    - name: Download Oracle JDK 20
      become: yes
      get_url:
        url: https://download.oracle.com/java/20/archive/jdk-20_linux-aarch64_bin.tar.gz
        dest: /tmp/jdk-20_linux-aarch64_bin.tar.gz
        mode: 0644

    - name: Extract Oracle JDK 20
      become: yes
      unarchive:
        src: /tmp/jdk-20_linux-aarch64_bin.tar.gz
        dest: /opt
        remote_src: yes
        creates: /opt/jdk-20

    - name: Execute the jar file
      shell: /opt/jdk-20/bin/java -jar -Dserver.port=8090 -Dserver.address=172.26.0.3 /opt/petclinic/spring-petclinic.jar

