---
- name: Configure web server
  hosts: web_server
  remote_user: runhaix
  gather_facts: no

  tasks:
    - name: Install required packages
      become: yes
      apt:
        name:
          - nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes
