---
- name: Deploy and run PetClinic application
  hosts: web_server
  remote_user: runhaix
  gather_facts: no

  tasks:
    - name: Create a directory for the PetClinic app
      become: yes
      file:
        path: /opt/petclinic
        state: directory

    - name: Fetch PetClinic JAR file from Jenkins
      delegate_to: localhost
      fetch:
        src: /var/jenkins_home/workspace/deploy_using_ansible/target/petclinic.jar
        dest: /tmp/petclinic.jar
        flat: yes

    - name: Copy PetClinic JAR file to target machine
      become: yes
      copy:
        src: /tmp/petclinic.jar
        dest: /opt/petclinic/spring-petclinic.jar
        mode: 0644

    - name: Kill existing PetClinic process
      become: yes
      shell: pkill -f spring-petclinic.jar || true

    - name: Run PetClinic application
      become: yes
      command: nohup java -jar /opt/petclinic/spring-petclinic.jar > /opt/petclinic/petclinic.log 2>&1 &
      args:
        chdir: /opt/petclinic
        creates: /opt/petclinic/petclinic.log
