---
- name: Deploy and run PetClinic application
  hosts: web_server
  remote_user: runhaix
  gather_facts: no

  tasks:
    - name: Create a directory for the PetClinic app
      become: yes
      file:
        path: /opt/petclinic
        state: directory

    - name: Synchronize PetClinic JAR file
      synchronize:
        src: /var/jenkins_home/workspace/petclinic_pipeline/target/petclinic.jar
        dest: /opt/petclinic/spring-petclinic.jar
        mode: push

    - name: Create PetClinic service file
      become: yes
      copy:
        content: |
          [Unit]
          Description=PetClinic App

          [Service]
          User=runhaix
          ExecStart=/usr/bin/java -jar /opt/petclinic/spring-petclinic.jar
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/petclinic.service

    - name: Reload systemd daemon
      become: yes
      systemd:
        daemon_reload: yes

    - name: Ensure PetClinic app is running and enabled
      become: yes
      systemd:
        name: petclinic
        state: started
        enabled: yes
