- name: Copy JAR file to container and execute
  hosts: web_server
  remote_user: runhaix
  tasks:
    - name: Copy JAR file to target container
      ansible.builtin.copy:
        src: /var/jenkins_home/workspace/deploy_using_ansible/target/petclinic.jar
        dest: /opt/petclinic/spring-petclinic.jar
        owner: runhaix
        group: runhaix
        mode: '0644'

    - name: Execute the jar file
      shell: java -jar -Dserver.port=8090 -Dserver.address=172.26.0.3 /opt/petclinic/spring-petclinic.jar
